///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tiki_AutomationTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Tiki_AutomationTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2f7139e6-f18b-440f-a925-5935a75279c2")]
    public partial class Tiki_AutomationTestRepository : RepoGenBaseFolder
    {
        static Tiki_AutomationTestRepository instance = new Tiki_AutomationTestRepository();
        Tiki_AutomationTestRepositoryFolders.HomePageAppFolder _homepage;
        Tiki_AutomationTestRepositoryFolders.LoginpopupAppFolder _loginpopup;
        Tiki_AutomationTestRepositoryFolders.RegisterByEmailAppFolder _registerbyemail;
        Tiki_AutomationTestRepositoryFolders.CreateNewAccountAppFolder _createnewaccount;
        Tiki_AutomationTestRepositoryFolders.AddToCartAppFolder _addtocart;

        /// <summary>
        /// Gets the singleton class instance representing the Tiki_AutomationTestRepository element repository.
        /// </summary>
        [RepositoryFolder("2f7139e6-f18b-440f-a925-5935a75279c2")]
        public static Tiki_AutomationTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Tiki_AutomationTestRepository() 
            : base("Tiki_AutomationTestRepository", "/", null, 0, false, "2f7139e6-f18b-440f-a925-5935a75279c2", ".\\RepositoryImages\\Tiki_AutomationTestRepository2f7139e6.rximgres")
        {
            _homepage = new Tiki_AutomationTestRepositoryFolders.HomePageAppFolder(this);
            _loginpopup = new Tiki_AutomationTestRepositoryFolders.LoginpopupAppFolder(this);
            _registerbyemail = new Tiki_AutomationTestRepositoryFolders.RegisterByEmailAppFolder(this);
            _createnewaccount = new Tiki_AutomationTestRepositoryFolders.CreateNewAccountAppFolder(this);
            _addtocart = new Tiki_AutomationTestRepositoryFolders.AddToCartAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2f7139e6-f18b-440f-a925-5935a75279c2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HomePage folder.
        /// </summary>
        [RepositoryFolder("ab50b38c-11a5-488e-9ccb-e804ebdb264a")]
        public virtual Tiki_AutomationTestRepositoryFolders.HomePageAppFolder HomePage
        {
            get { return _homepage; }
        }

        /// <summary>
        /// The Loginpopup folder.
        /// </summary>
        [RepositoryFolder("95ee8582-bc1d-48d6-8338-08797f840d80")]
        public virtual Tiki_AutomationTestRepositoryFolders.LoginpopupAppFolder Loginpopup
        {
            get { return _loginpopup; }
        }

        /// <summary>
        /// The RegisterByEmail folder.
        /// </summary>
        [RepositoryFolder("86a4c5a9-729a-4a9b-b63f-125b144a8e80")]
        public virtual Tiki_AutomationTestRepositoryFolders.RegisterByEmailAppFolder RegisterByEmail
        {
            get { return _registerbyemail; }
        }

        /// <summary>
        /// The CreateNewAccount folder.
        /// </summary>
        [RepositoryFolder("be887eff-1fe8-459a-8155-1b7d41c8a36c")]
        public virtual Tiki_AutomationTestRepositoryFolders.CreateNewAccountAppFolder CreateNewAccount
        {
            get { return _createnewaccount; }
        }

        /// <summary>
        /// The AddToCart folder.
        /// </summary>
        [RepositoryFolder("4d682aab-9367-4053-92e7-32f4a3c5a0f1")]
        public virtual Tiki_AutomationTestRepositoryFolders.AddToCartAppFolder AddToCart
        {
            get { return _addtocart; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Tiki_AutomationTestRepositoryFolders
    {
        /// <summary>
        /// The HomePageAppFolder folder.
        /// </summary>
        [RepositoryFolder("ab50b38c-11a5-488e-9ccb-e804ebdb264a")]
        public partial class HomePageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnsearchInfo;
            RepoItemInfo _txtsearchInfo;
            RepoItemInfo _btnregiterInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "/dom[@domain='tiki.vn']", parentFolder, 30000, null, false, "ab50b38c-11a5-488e-9ccb-e804ebdb264a", "")
            {
                _btnsearchInfo = new RepoItemInfo(this, "btnSearch", ".//button[@innertext='Tìm Kiếm']", ".//div[#'__next']//button[@innertext='Tìm Kiếm']", 30000, null, "59a4b0e4-5a21-4755-8f3d-8760ad66b1e5");
                _txtsearchInfo = new RepoItemInfo(this, "txtSearch", ".//input[@type='text']", ".//div[#'__next']//input[@type='text']", 30000, null, "95c89f98-d9b9-4e92-91cb-ef65c785d769");
                _btnregiterInfo = new RepoItemInfo(this, "btnRegiter", ".//span[@innertext='Đăng Nhập / Đăng Ký']", ".//div[#'__next']//span[@innertext='Đăng Nhập / Đăng Ký']", 30000, null, "70d0ffb2-2d93-4905-97c0-d2e72b52767a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ab50b38c-11a5-488e-9ccb-e804ebdb264a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ab50b38c-11a5-488e-9ccb-e804ebdb264a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The btnSearch item.
            /// </summary>
            [RepositoryItem("59a4b0e4-5a21-4755-8f3d-8760ad66b1e5")]
            public virtual Ranorex.Button btnSearch
            {
                get
                {
                    return _btnsearchInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnSearch item info.
            /// </summary>
            [RepositoryItemInfo("59a4b0e4-5a21-4755-8f3d-8760ad66b1e5")]
            public virtual RepoItemInfo btnSearchInfo
            {
                get
                {
                    return _btnsearchInfo;
                }
            }

            /// <summary>
            /// The txtSearch item.
            /// </summary>
            [RepositoryItem("95c89f98-d9b9-4e92-91cb-ef65c785d769")]
            public virtual Ranorex.InputTag txtSearch
            {
                get
                {
                    return _txtsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtSearch item info.
            /// </summary>
            [RepositoryItemInfo("95c89f98-d9b9-4e92-91cb-ef65c785d769")]
            public virtual RepoItemInfo txtSearchInfo
            {
                get
                {
                    return _txtsearchInfo;
                }
            }

            /// <summary>
            /// The btnRegiter item.
            /// </summary>
            [RepositoryItem("70d0ffb2-2d93-4905-97c0-d2e72b52767a")]
            public virtual Ranorex.SpanTag btnRegiter
            {
                get
                {
                    return _btnregiterInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The btnRegiter item info.
            /// </summary>
            [RepositoryItemInfo("70d0ffb2-2d93-4905-97c0-d2e72b52767a")]
            public virtual RepoItemInfo btnRegiterInfo
            {
                get
                {
                    return _btnregiterInfo;
                }
            }
        }

        /// <summary>
        /// The LoginpopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("95ee8582-bc1d-48d6-8338-08797f840d80")]
        public partial class LoginpopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtphoneInfo;
            RepoItemInfo _btncontinueInfo;
            RepoItemInfo _emailregistInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new Loginpopup  folder.
            /// </summary>
            public LoginpopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Loginpopup", "/dom[@domain='tiki.vn']", parentFolder, 30000, null, false, "95ee8582-bc1d-48d6-8338-08797f840d80", "")
            {
                _txtphoneInfo = new RepoItemInfo(this, "txtPhone", ".//input[@name='tel']", "element", 30000, null, "354ab2cb-7350-47fd-9ecd-c55f129e9801");
                _btncontinueInfo = new RepoItemInfo(this, "btnContinue", ".//button[@innertext='Tiếp Tục']", "element", 30000, null, "09c3a1fc-0f9d-4a62-a936-6120b779c434");
                _emailregistInfo = new RepoItemInfo(this, "EmailRegist", ".//p[@innertext='Đăng nhập bằng email']", ".//p[@innertext='Đăng nhập bằng email']", 30000, null, "1b45f5dd-a424-415e-893e-b99182dababa");
                _txtpasswordInfo = new RepoItemInfo(this, "txtPassWord", ".//input[@type='password']", ".//input[@type='password']", 30000, null, "a6503f99-27c4-49cb-b904-b4ed4f76b385");
                _btnloginInfo = new RepoItemInfo(this, "btnLogin", ".//button[@innertext='Đăng Nhập']", ".//button[@innertext='Đăng Nhập']", 30000, null, "cbfc013e-e95f-4743-b0fb-ec573689280a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95ee8582-bc1d-48d6-8338-08797f840d80")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95ee8582-bc1d-48d6-8338-08797f840d80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtPhone item.
            /// </summary>
            [RepositoryItem("354ab2cb-7350-47fd-9ecd-c55f129e9801")]
            public virtual Ranorex.InputTag txtPhone
            {
                get
                {
                    return _txtphoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPhone item info.
            /// </summary>
            [RepositoryItemInfo("354ab2cb-7350-47fd-9ecd-c55f129e9801")]
            public virtual RepoItemInfo txtPhoneInfo
            {
                get
                {
                    return _txtphoneInfo;
                }
            }

            /// <summary>
            /// The btnContinue item.
            /// </summary>
            [RepositoryItem("09c3a1fc-0f9d-4a62-a936-6120b779c434")]
            public virtual Ranorex.Button btnContinue
            {
                get
                {
                    return _btncontinueInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnContinue item info.
            /// </summary>
            [RepositoryItemInfo("09c3a1fc-0f9d-4a62-a936-6120b779c434")]
            public virtual RepoItemInfo btnContinueInfo
            {
                get
                {
                    return _btncontinueInfo;
                }
            }

            /// <summary>
            /// The EmailRegist item.
            /// </summary>
            [RepositoryItem("1b45f5dd-a424-415e-893e-b99182dababa")]
            public virtual Ranorex.PTag EmailRegist
            {
                get
                {
                    return _emailregistInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The EmailRegist item info.
            /// </summary>
            [RepositoryItemInfo("1b45f5dd-a424-415e-893e-b99182dababa")]
            public virtual RepoItemInfo EmailRegistInfo
            {
                get
                {
                    return _emailregistInfo;
                }
            }

            /// <summary>
            /// The txtPassWord item.
            /// </summary>
            [RepositoryItem("a6503f99-27c4-49cb-b904-b4ed4f76b385")]
            public virtual Ranorex.InputTag txtPassWord
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtPassWord item info.
            /// </summary>
            [RepositoryItemInfo("a6503f99-27c4-49cb-b904-b4ed4f76b385")]
            public virtual RepoItemInfo txtPassWordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The btnLogin item.
            /// </summary>
            [RepositoryItem("cbfc013e-e95f-4743-b0fb-ec573689280a")]
            public virtual Ranorex.Button btnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLogin item info.
            /// </summary>
            [RepositoryItemInfo("cbfc013e-e95f-4743-b0fb-ec573689280a")]
            public virtual RepoItemInfo btnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The RegisterByEmailAppFolder folder.
        /// </summary>
        [RepositoryFolder("86a4c5a9-729a-4a9b-b63f-125b144a8e80")]
        public partial class RegisterByEmailAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtemailInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new RegisterByEmail  folder.
            /// </summary>
            public RegisterByEmailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterByEmail", "/dom[@domain='tiki.vn']", parentFolder, 30000, null, false, "86a4c5a9-729a-4a9b-b63f-125b144a8e80", "")
            {
                _txtemailInfo = new RepoItemInfo(this, "txtEmail", ".//input[@name='email']", ".//input[@name='email']", 30000, null, "6f6fd175-a995-4eda-87da-7e747cdf5fdb");
                _txtpasswordInfo = new RepoItemInfo(this, "txtpassword", ".//input[@type='password']", ".//input[@type='password']", 30000, null, "0f8fbd35-338f-4e9d-a76a-3f7f8f48e5eb");
                _btnloginInfo = new RepoItemInfo(this, "btnLogin", ".//button[@innertext='Đăng nhập']", ".//button[@innertext='Đăng nhập']", 30000, null, "f09fa888-e3e1-4fb2-ba5f-d7d70144ab09");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86a4c5a9-729a-4a9b-b63f-125b144a8e80")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86a4c5a9-729a-4a9b-b63f-125b144a8e80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtEmail item.
            /// </summary>
            [RepositoryItem("6f6fd175-a995-4eda-87da-7e747cdf5fdb")]
            public virtual Ranorex.InputTag txtEmail
            {
                get
                {
                    return _txtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtEmail item info.
            /// </summary>
            [RepositoryItemInfo("6f6fd175-a995-4eda-87da-7e747cdf5fdb")]
            public virtual RepoItemInfo txtEmailInfo
            {
                get
                {
                    return _txtemailInfo;
                }
            }

            /// <summary>
            /// The txtpassword item.
            /// </summary>
            [RepositoryItem("0f8fbd35-338f-4e9d-a76a-3f7f8f48e5eb")]
            public virtual Ranorex.InputTag txtpassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtpassword item info.
            /// </summary>
            [RepositoryItemInfo("0f8fbd35-338f-4e9d-a76a-3f7f8f48e5eb")]
            public virtual RepoItemInfo txtpasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The btnLogin item.
            /// </summary>
            [RepositoryItem("f09fa888-e3e1-4fb2-ba5f-d7d70144ab09")]
            public virtual Ranorex.Button btnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnLogin item info.
            /// </summary>
            [RepositoryItemInfo("f09fa888-e3e1-4fb2-ba5f-d7d70144ab09")]
            public virtual RepoItemInfo btnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The CreateNewAccountAppFolder folder.
        /// </summary>
        [RepositoryFolder("be887eff-1fe8-459a-8155-1b7d41c8a36c")]
        public partial class CreateNewAccountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spancreateInfo;

            /// <summary>
            /// Creates a new CreateNewAccount  folder.
            /// </summary>
            public CreateNewAccountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewAccount", "/dom[@domain='tiki.vn']", parentFolder, 30000, null, false, "be887eff-1fe8-459a-8155-1b7d41c8a36c", "")
            {
                _spancreateInfo = new RepoItemInfo(this, "spanCreate", ".//span[@innertext='Tạo tài khoản']", ".//span[@innertext='Tạo tài khoản']", 30000, null, "78d6d39b-ffd6-43c0-a3fd-2f45c2c67cc2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be887eff-1fe8-459a-8155-1b7d41c8a36c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be887eff-1fe8-459a-8155-1b7d41c8a36c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The spanCreate item.
            /// </summary>
            [RepositoryItem("78d6d39b-ffd6-43c0-a3fd-2f45c2c67cc2")]
            public virtual Ranorex.SpanTag spanCreate
            {
                get
                {
                    return _spancreateInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The spanCreate item info.
            /// </summary>
            [RepositoryItemInfo("78d6d39b-ffd6-43c0-a3fd-2f45c2c67cc2")]
            public virtual RepoItemInfo spanCreateInfo
            {
                get
                {
                    return _spancreateInfo;
                }
            }
        }

        /// <summary>
        /// The AddToCartAppFolder folder.
        /// </summary>
        [RepositoryFolder("4d682aab-9367-4053-92e7-32f4a3c5a0f1")]
        public partial class AddToCartAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productmenuInfo;
            RepoItemInfo _productitemInfo;
            RepoItemInfo _btnaddtocartInfo;

            /// <summary>
            /// Creates a new AddToCart  folder.
            /// </summary>
            public AddToCartAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddToCart", "/dom[@domain='tiki.vn']", parentFolder, 30000, null, false, "4d682aab-9367-4053-92e7-32f4a3c5a0f1", "")
            {
                _productmenuInfo = new RepoItemInfo(this, "ProductMenu", ".//div[@innertext='Bách Hóa']", ".//div[#'__next']//div[@innertext='Bách Hóa']", 30000, null, "76d04655-b9b4-4b2b-b47d-cd586e14424f");
                _productitemInfo = new RepoItemInfo(this, "ProductItem", ".//span[@innertext>'Thùng 24 Cà phê lon Cà Phê']", ".//div[#'__next']//span[@innertext>'Thùng 24 Cà phê lon Cà Phê']", 30000, null, "e3863d8e-ddec-4625-9b11-ad6f1441e53a");
                _btnaddtocartInfo = new RepoItemInfo(this, "btnAddToCart", ".//button[@innertext='Chọn mua']", "", 30000, null, "c8d0d5ea-5d43-498d-be86-0df48e31d2af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d682aab-9367-4053-92e7-32f4a3c5a0f1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d682aab-9367-4053-92e7-32f4a3c5a0f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductMenu item.
            /// </summary>
            [RepositoryItem("76d04655-b9b4-4b2b-b47d-cd586e14424f")]
            public virtual Ranorex.DivTag ProductMenu
            {
                get
                {
                    return _productmenuInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductMenu item info.
            /// </summary>
            [RepositoryItemInfo("76d04655-b9b4-4b2b-b47d-cd586e14424f")]
            public virtual RepoItemInfo ProductMenuInfo
            {
                get
                {
                    return _productmenuInfo;
                }
            }

            /// <summary>
            /// The ProductItem item.
            /// </summary>
            [RepositoryItem("e3863d8e-ddec-4625-9b11-ad6f1441e53a")]
            public virtual Ranorex.SpanTag ProductItem
            {
                get
                {
                    return _productitemInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProductItem item info.
            /// </summary>
            [RepositoryItemInfo("e3863d8e-ddec-4625-9b11-ad6f1441e53a")]
            public virtual RepoItemInfo ProductItemInfo
            {
                get
                {
                    return _productitemInfo;
                }
            }

            /// <summary>
            /// The btnAddToCart item.
            /// </summary>
            [RepositoryItem("c8d0d5ea-5d43-498d-be86-0df48e31d2af")]
            public virtual Ranorex.Button btnAddToCart
            {
                get
                {
                    return _btnaddtocartInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The btnAddToCart item info.
            /// </summary>
            [RepositoryItemInfo("c8d0d5ea-5d43-498d-be86-0df48e31d2af")]
            public virtual RepoItemInfo btnAddToCartInfo
            {
                get
                {
                    return _btnaddtocartInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
